/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ComparisonMetric = IDL.Record({
  'installationTime' : IDL.Text,
  'waterControl' : IDL.Text,
  'maxHeight' : IDL.Float64,
  'deflection' : IDL.Text,
  'systemId' : IDL.Text,
  'mobilizationTime' : IDL.Text,
  'noisyVibration' : IDL.Text,
  'costRange' : IDL.Text,
});
export const ResearchPaper = IDL.Record({
  'id' : IDL.Text,
  'categories' : IDL.Vec(IDL.Text),
  'method' : IDL.Text,
  'title' : IDL.Text,
  'doiLink' : IDL.Text,
  'keyParameters' : IDL.Text,
  'abstract' : IDL.Text,
});
export const SystemDetail = IDL.Record({
  'content' : IDL.Text,
  'tabName' : IDL.Text,
  'systemId' : IDL.Text,
});
export const WallType = IDL.Variant({
  'TangentPile' : IDL.Null,
  'SheetPile' : IDL.Null,
  'SecantPile' : IDL.Null,
  'DiaphragmWall' : IDL.Null,
  'Micropile' : IDL.Null,
  'SoldierPile' : IDL.Null,
});
export const ExcavationSystem = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'wallType' : WallType,
});

export const idlService = IDL.Service({
  'getAllMetrics' : IDL.Func([], [IDL.Vec(ComparisonMetric)], ['query']),
  'getPapers' : IDL.Func([], [IDL.Vec(ResearchPaper)], ['query']),
  'getPapersByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ResearchPaper)],
      ['query'],
    ),
  'getSystemDetail' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(SystemDetail)],
      ['query'],
    ),
  'getSystems' : IDL.Func([], [IDL.Vec(ExcavationSystem)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ComparisonMetric = IDL.Record({
    'installationTime' : IDL.Text,
    'waterControl' : IDL.Text,
    'maxHeight' : IDL.Float64,
    'deflection' : IDL.Text,
    'systemId' : IDL.Text,
    'mobilizationTime' : IDL.Text,
    'noisyVibration' : IDL.Text,
    'costRange' : IDL.Text,
  });
  const ResearchPaper = IDL.Record({
    'id' : IDL.Text,
    'categories' : IDL.Vec(IDL.Text),
    'method' : IDL.Text,
    'title' : IDL.Text,
    'doiLink' : IDL.Text,
    'keyParameters' : IDL.Text,
    'abstract' : IDL.Text,
  });
  const SystemDetail = IDL.Record({
    'content' : IDL.Text,
    'tabName' : IDL.Text,
    'systemId' : IDL.Text,
  });
  const WallType = IDL.Variant({
    'TangentPile' : IDL.Null,
    'SheetPile' : IDL.Null,
    'SecantPile' : IDL.Null,
    'DiaphragmWall' : IDL.Null,
    'Micropile' : IDL.Null,
    'SoldierPile' : IDL.Null,
  });
  const ExcavationSystem = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'wallType' : WallType,
  });
  
  return IDL.Service({
    'getAllMetrics' : IDL.Func([], [IDL.Vec(ComparisonMetric)], ['query']),
    'getPapers' : IDL.Func([], [IDL.Vec(ResearchPaper)], ['query']),
    'getPapersByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ResearchPaper)],
        ['query'],
      ),
    'getSystemDetail' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(SystemDetail)],
        ['query'],
      ),
    'getSystems' : IDL.Func([], [IDL.Vec(ExcavationSystem)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };