/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ComparisonMetric {
  'installationTime' : string,
  'waterControl' : string,
  'maxHeight' : number,
  'deflection' : string,
  'systemId' : string,
  'mobilizationTime' : string,
  'noisyVibration' : string,
  'costRange' : string,
}
export interface ExcavationSystem {
  'id' : string,
  'name' : string,
  'description' : string,
  'wallType' : WallType,
}
export interface ResearchPaper {
  'id' : string,
  'categories' : Array<string>,
  'method' : string,
  'title' : string,
  'doiLink' : string,
  'keyParameters' : string,
  'abstract' : string,
}
export interface SystemDetail {
  'content' : string,
  'tabName' : string,
  'systemId' : string,
}
export type WallType = { 'TangentPile' : null } |
  { 'SheetPile' : null } |
  { 'SecantPile' : null } |
  { 'DiaphragmWall' : null } |
  { 'Micropile' : null } |
  { 'SoldierPile' : null };
export interface _SERVICE {
  'getAllMetrics' : ActorMethod<[], Array<ComparisonMetric>>,
  'getPapers' : ActorMethod<[], Array<ResearchPaper>>,
  'getPapersByCategory' : ActorMethod<[string], Array<ResearchPaper>>,
  'getSystemDetail' : ActorMethod<[string, string], [] | [SystemDetail]>,
  'getSystems' : ActorMethod<[], Array<ExcavationSystem>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];