/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ComparisonMetric {
    installationTime: string;
    waterControl: string;
    maxHeight: number;
    deflection: string;
    systemId: string;
    mobilizationTime: string;
    noisyVibration: string;
    costRange: string;
}
export interface ExcavationSystem {
    id: string;
    name: string;
    description: string;
    wallType: WallType;
}
export interface ResearchPaper {
    id: string;
    categories: Array<string>;
    method: string;
    title: string;
    doiLink: string;
    keyParameters: string;
    abstract: string;
}
export interface SystemDetail {
    content: string;
    tabName: string;
    systemId: string;
}
export enum WallType {
    TangentPile = "TangentPile",
    SheetPile = "SheetPile",
    SecantPile = "SecantPile",
    DiaphragmWall = "DiaphragmWall",
    Micropile = "Micropile",
    SoldierPile = "SoldierPile"
}
export interface backendInterface {
    getAllMetrics(): Promise<Array<ComparisonMetric>>;
    getPapers(): Promise<Array<ResearchPaper>>;
    getPapersByCategory(category: string): Promise<Array<ResearchPaper>>;
    getSystemDetail(systemId: string, tab: string): Promise<SystemDetail | null>;
    getSystems(): Promise<Array<ExcavationSystem>>;
}
import type { ExcavationSystem as _ExcavationSystem, SystemDetail as _SystemDetail, WallType as _WallType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllMetrics(): Promise<Array<ComparisonMetric>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMetrics();
            return result;
        }
    }
    async getPapers(): Promise<Array<ResearchPaper>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPapers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPapers();
            return result;
        }
    }
    async getPapersByCategory(arg0: string): Promise<Array<ResearchPaper>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPapersByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPapersByCategory(arg0);
            return result;
        }
    }
    async getSystemDetail(arg0: string, arg1: string): Promise<SystemDetail | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSystemDetail(arg0, arg1);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSystemDetail(arg0, arg1);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSystems(): Promise<Array<ExcavationSystem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSystems();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSystems();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ExcavationSystem_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExcavationSystem): ExcavationSystem {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_WallType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WallType): WallType {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SystemDetail]): SystemDetail | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    description: string;
    wallType: _WallType;
}): {
    id: string;
    name: string;
    description: string;
    wallType: WallType;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        wallType: from_candid_WallType_n5(_uploadFile, _downloadFile, value.wallType)
    };
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    TangentPile: null;
} | {
    SheetPile: null;
} | {
    SecantPile: null;
} | {
    DiaphragmWall: null;
} | {
    Micropile: null;
} | {
    SoldierPile: null;
}): WallType {
    return "TangentPile" in value ? WallType.TangentPile : "SheetPile" in value ? WallType.SheetPile : "SecantPile" in value ? WallType.SecantPile : "DiaphragmWall" in value ? WallType.DiaphragmWall : "Micropile" in value ? WallType.Micropile : "SoldierPile" in value ? WallType.SoldierPile : value;
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExcavationSystem>): Array<ExcavationSystem> {
    return value.map((x)=>from_candid_ExcavationSystem_n3(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
